Fix normalisation of power spectra density when `chunks_to_segments=True`
xgcm/xrft pull request #103
Opened 2020-08-26 05:54 UTC by dougiesquire

# Description

The term `N` in the `density=True` normalisation is computed from the chunk sizes rather than dimension sizes when `chunks_to_segments=True`.

Closes #102

## Type of change

-   [x]  Bug fix (non-breaking change which fixes an issue)

## Testing 

- [x] Extended `test_parseval()` to include checks with `chunks_to_segments=True`

2020-09-01 04:24 UTC, dougiesquire commented
Ready for review @rabernat

2020-09-09 14:46 UTC, rabernat requested changes
This is looking great! Thanks @dougiesquire! Just a few small comments / questions.

Sorry for the slow review.

2020-09-09 14:46 UTC, rabernat commented on xrft/xrft.py
> +        N = [da.chunks[n][0] for n in axis_num]
Since this code block  is re-used in two places functions, maybe we could put it in a small standalone function, with the signature

```python
def _calc_normalization_factor(da, axis_num, chunks_to_segments):
```

2020-09-09 14:46 UTC, rabernat commented on xrft/tests/test_xrft.py
> +    )
I guess this complex window is necessary to provide a reference "truth" against which to compare the results of xrft?

In general, I'd like to see a few comments in this test to help the other devs understand what's happening better.

2020-09-10 01:49 UTC, dougiesquire commented on xrft/tests/test_xrft.py
> +    )
That's right - this is to account for the energy reduction resulting from windowing (see also https://github.com/xgcm/xrft/issues/104). 

I've added some comments and made some small changes to `test_parseval` that make it clearer (at least to me...)

2020-09-10 13:07 UTC, rabernat commented
Fantastic! Thank you!

2020-09-10 13:07 UTC, merged