Moving spacing as coords attribute + some update
xgcm/xrft pull request #126
Opened 2020-11-19 23:07 UTC by lanougue

spacing information is currently added as a new coordinate into dft output. I believe it is a strange behaviour.
In this PR, I move frequency spacing information as an attribute of the coordinate itself.
It allows to recall spacing information with:
S = xrft.dft(..., dim='x')
print(S.freq_x.spacing)

Stored as a coordinate attribute, spacing information is kept while doing some operation on xarray S. Moreover, there is now a unique name "spacing".

There was also a bug in _new_dims_and_coords() when called on xarrays with dimensions without coordinates. I propose a simpler version of _new_dims_and_coords() without this bug.

2020-11-19 23:19 UTC, lanougue commented
@roxyboy , @rabernat . If you are ok with that, I can start updating the tests who check spacing variable

2020-11-20 10:54 UTC, roxyboy commented
@lanougue if you want to check if the tests work locally, you can also always run `pytest xrft -v` in the top directory of `xrft`.

2020-11-20 11:07 UTC, lanougue commented
> @lanougue if you want to check if the tests work locally, you can also always run `pytest xrft -v` in the top directory of `xrft`.

Thanks ! I did not know about that ;)

2020-11-20 22:05 UTC, lanougue commented
To summerize:

1) spacing (currently assign as a new coordinate) are now defined as an attribute  of the corresponding coordinate. The spacing of all transformed dimensions are all named "spacing" but they can be rercovered through their respective coordinate : output.freq_x.spacing is the spacing of freq_x

2) No more bug when calling transform on dimension without coordinate. (Strange because I have seen a test somewhere to check that). It rresolve bug1 of #127 

3) _new_dims_and_coords() function simplified

2020-11-22 21:07 UTC, lanougue commented
This last commit solves bug2 of #127. No more problem when calling the real transform whose dim is not listed as last argument of dim list.
I added simplifications of transpose operation without defining again the new name of transformed coordinates. It is now automatic.
Sorry for adding modifications in this PR which are not related to "moving spacing attribues"...

2020-11-23 01:12 UTC, rabernat commented on xrft/xrft.py
> +# return da, trans
No commented-out code please. Just remove the function if it is unnecessary. Git keeps the entire code history.

2020-11-23 01:14 UTC, rabernat commented on xrft/xrft.py
> +                "The dimension along real FT is taken must be one of the existing dimensions."
```suggestion
                "The dimension along which real FT is taken must be one of the existing dimensions."
```

2020-11-23 01:14 UTC, rabernat commented on xrft/tests/test_xrft.py
> +    # expected = expected.assign_coords(freq_x_spacing=1 / (len(x) * dx))
No commented-out  code.

2020-11-23 01:16 UTC, rabernat requested changes
This is great. Thanks for taking the time to clean up and simplify the code. Just some minor nit-picks.

2020-11-30 17:26 UTC, lanougue commented
Hi @rabernat, What do you think about these changes ?

2020-11-30 17:29 UTC, rabernat commented
Fantastic, thank you!

2020-11-30 17:29 UTC, merged