Adding idft
xgcm/xrft pull request #129
Opened 2020-12-04 16:37 UTC by lanougue

Adding new function idft to do inverse Fourier Transform

2020-12-04 16:47 UTC, lanougue commented
Here is an addition of the idft function. True_phase option is also available to do correct phase inversion. A new argument "lag" is also added to allow the user to have arbitrary output coordinates.

I can add tests. What kind of tests do you think are relevant ?
I think that the two tests below should be done:
- idft(dft(S)) == S
- idft(dft(S, true_phase=True), true_phase=True) == S

2020-12-07 14:58 UTC, roxyboy commented
> I think that the two tests below should be done:
> 
> * idft(dft(S)) == S
> * idft(dft(S, true_phase=True), true_phase=True) == S

I agree with this.

2020-12-07 15:02 UTC, roxyboy commented on xrft/xrft.py
> +    da,
@lanougue Can you change the docstring so that it explains `idft`? I think the input should be named as `daft` and output as `da` to be consistent with `dft`.

2020-12-07 17:54 UTC, lanougue commented on xrft/xrft.py
> +    da,
Ok, I will wait for discussion #130 to go to a decision before continuing

2020-12-08 19:19 UTC, roxyboy commented on xrft/xrft.py
> +    da,
Should we also have a `xrft.ifft` function...?

2020-12-08 20:19 UTC, lanougue commented on xrft/xrft.py
> +    da,
I think so. It is in the plan too

2020-12-10 17:33 UTC, lanougue commented
I am almost done,
I still have a question on how to resolve some tests. I want to check what happen if a user try to do: ifft(fft(s))

If the user try idft(dft(s)) with true_phase and true_amplitude set to True for both transformations, he will recover the original signal "s". No problem.

However, ifft(fft(s)) will almost never be equal to s. This is because initial coordinates of "s" (and thus the phase) have been lost during the operation. Thus, coordinates of "s" and "ifft(fft(s))" will never match (it will match only if "s" coordinates are centered (meaning phase=0). However, s.data and ifft(fft(s)).data match as with numpy.
(shifting operation can yet alter this equality).

I think this is a totally normal behaviour, but can be disturbing for a user who always tough that ifft(fft(s))==s. It is true for amplitude but this is not the case anymore for the coordinates unless they are correctly taken into account during both transformations (as with dft() and true_phase flag).

In an xarray framework, the unique option to have idft(dft(s))==s for both amplitude and coordinates is to convince people to abandon fft to go to dft.

2020-12-10 17:40 UTC, roxyboy commented
> However, s.data and ifft(fft(s)).data match as with numpy.

Thanks for your work @lanougue ! I'm in favor of `s.data = ifft(fft(s)).data` as that is what one would also expect from numpy.

2020-12-10 17:43 UTC, roxyboy commented
@lanougue I think you can have `xrft.ifft` raise a warning about the coordinate information getting lost in the operation and recommend the usage of `xrft.idft`.

2020-12-11 13:55 UTC, lanougue commented
Done.
In all functions I change dft calls into fft calls to keep consistency with current xrft behaviour.
It could be interesting to let the user choose between fft or dft call in other functions such as power_spectrum, cross_spectrum, ...

2020-12-11 14:03 UTC, roxyboy reviewed
@lanougue I think these changes are great! My suggestions are only minor. Also could you add the testing of Parseval's identity with the amplitude and phase being set to True? There's already a test function (`test_parseval`) that checks for it using `xrft.power_spectrum` so you could probably add it there.

2020-12-11 14:03 UTC, roxyboy commented on xrft/xrft.py
> +        print("true_phase argument is ignored in xrft.fft")
I generally think making functions print messages is not standard. Could you change these to warnings?

2020-12-11 14:03 UTC, roxyboy commented on xrft/xrft.py
>      daft : `xarray.DataArray`
Can we change the output from daft to da and the input to daft?

2020-12-11 14:12 UTC, roxyboy commented on xrft/xrft.py
> +        msg = "xrft.dft default behaviour will be modified in future versions of xrft. Prefer xrft.fft to ensure future compatibility and deactivate this warning. Consider using xrft.dft for accurate
Maybe we could phrase this like: "The flags `true_phase` and `true_amplitude` will be set to True in future versions of xrft to preserve the theoretical phasing and amplitude of FT. Consider using xrft.fft to ensure future compatibility with numpy.fft like behavior and to deactivate this warning."

2020-12-11 14:16 UTC, roxyboy commented on xrft/xrft.py
> +    msg = "xrft.ifft do not guaranty output coordinate phasing. Prefer xrft.dft and xrft.idft as forward and backward Fourier Transforms with true_phase flag set to True for accurate coordinates hand
A small typo: does not guarantee correct coordinate phasing for its output. We recommend... with the true_phase flag set to True... coordinate handling.

2020-12-11 14:31 UTC, roxyboy commented
> It could be interesting to let the user choose between fft or dft call in other functions such as power_spectrum, cross_spectrum, ...

I agree with this. Could we just add the true_phase and true_amplitude flags to power_spectrum and cross_spectrum by also keeping the default as False?

2020-12-11 18:36 UTC, roxyboy requested changes

2020-12-11 18:36 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +
Thanks for adding the tests. Can you put these to the test that already existed as `test_parseval`?

2020-12-11 18:36 UTC, lanougue commented
Hi @roxyboy ,
Thanks for your review. I think I did all the changes you have suggested.
I recreated two very small tests (1D and 2D) for the parseval identity checking with dft and true flags.
I did not use existing test_parseval function because this later tests several other things at the same time (windowing, ...)

Adding true_phase and true_amplitude flags in power_spectrum and cross_spectrum is feasible (fft call should be transformed into dft call). However, output phase and amplitude will of course be modified and we should evaluate the impact of these modifications in these functions (which is probably also desirable too).

2020-12-11 18:41 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +
@lanougue It starts from line 548 of test_xrft.py.

2020-12-11 18:55 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +        (np.abs(s) ** 2).sum() * dx, (np.abs(FTs) ** 2).sum() * FTs["freq_x"].spacing
I think by adding the phase and amplitude flags to power_spectrum, we could change this line to use that instead?

2020-12-12 10:02 UTC, roxyboy commented on xrft/xrft.py
>          fft_fn = fftm.irfftn
I'm now wondering what would happen if `real` is not None but the phase and amplitude flags are set to True...

2020-12-13 21:00 UTC, lanougue commented on xrft/tests/test_xrft.py
> +        (np.abs(s) ** 2).sum() * dx, (np.abs(FTs) ** 2).sum() * FTs["freq_x"].spacing
In test_parseval, line 584, 609, 623, 638, ... power spectrum is divided by the spacing(s). This normalisation should not be applied in case of true_phase/amplitude flags used.
Adding each time an "if" condition in case of flags being used starts to complicate the code. Don't you think we could have a better way ?

2020-12-13 21:06 UTC, roxyboy commented
> Adding true_phase and true_amplitude flags in power_spectrum and cross_spectrum is feasible (fft call should be transformed into dft call). However, output phase and amplitude will of course be modified and we should evaluate the impact of these modifications in these functions (which is probably also desirable too).

Considering that we already tests checking for Parseval when the flags were False (the current dft), I think the tests to be added should be only for when the flags are True. This would reduce the complexity of if statements.

2020-12-13 21:14 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +        (np.abs(s) ** 2).sum() * dx, (np.abs(FTs) ** 2).sum() * FTs["freq_x"].spacing
Considering that we already had tests checking for Parseval when the flags were False (the current dft), I think the tests to be added should be only for when the flags are True. This would reduce the complexity of if statements.

2020-12-13 22:05 UTC, lanougue commented on xrft/xrft.py
>          fft_fn = fftm.irfftn
I checked and it was not fine. This new PR should be ok now. I had to create an irfftfreq function which, strangely, is not a standard numpy function.

2020-12-14 11:36 UTC, roxyboy commented on xrft/xrft.py
>          fft_fn = fftm.irfftn
Thanks for looking into this. Can we also add a test for real dft with the flags being set to True?

2020-12-14 12:14 UTC, lanougue commented
I am simplifying and adding true_flags possibilities to (co, cross and phase of) spectrum.

I have remaing questions:
* Why cross_spectrum is returning only the real part ? I think that the imaginary part is as important as the real one. Shouln't we return the complex spectrum ?
* In computing cross_phase, I used xr.ufuncs.angle() to compute the phase. I think it automattically handle all dask and chunk stuff.
* What the return of power_spectrum with density flags set to False means ? Shouldn't we use the same syntax of "scipy.signal.periodogram" with a scaling flag set to "density" or "spectrum" ?

(@roxyboy : sorry for the failing checks, my local pytest is not working for now)

2020-12-14 12:23 UTC, roxyboy requested changes

2020-12-14 12:23 UTC, roxyboy commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
I think we should have an `if` statement here about the phase and amplitude flags. If density is set to True, it should satisfy Parseval regardless of the phase and amplitude flags.

2020-12-14 12:23 UTC, roxyboy commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
Same as in power_spectrum regarding the phase and amplitude flags.

2020-12-14 12:23 UTC, roxyboy commented on xrft/xrft.py
> +    cp = xr.ufuncs.angle(daft1 * np.conj(daft2))
I wasn't able to find the documentation about this on Google but could you provide the link for it so I can see what it's intended to do?

2020-12-14 12:27 UTC, lanougue commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
Your are right, when density is True, true_flags do not matter. However, what density =False means ? Should we replace the density flag by a scaling flag as noted in my previous comment ?

2020-12-14 12:27 UTC, roxyboy commented
> * Why cross_spectrum is returning only the real part ? I think that the imaginary part is as important as the real one. Shouln't we return the complex spectrum ?
> * What the return of power_spectrum with density flags set to False means ? Shouldn't we use the same syntax of "scipy.signal.periodogram" with a scaling flag set to "density" or "spectrum" ?

Thanks for all the work @lanougue ! I think we're almost there. Regarding your point about cross spectrum, when I coded it up, I was only interested in the amplitude, which is why I ended up returning the real part only. If you think having the imaginary part would benefit users, I'm fine with returning the complex results.

As for the scaling flag, you're point makes sense but again, changing this flag would break the default users for current users... Essentially, `density=True` should be equivalent to `scaling=density`.

2020-12-14 12:29 UTC, lanougue commented
Yes, this is why I suggest to change this flag into a scaling flag (with a deprecated warning) since I beleive no one was using the density flag set to False

2020-12-14 12:32 UTC, lanougue commented on xrft/xrft.py
> +    cp = xr.ufuncs.angle(daft1 * np.conj(daft2))
http://xarray.pydata.org/en/stable/generated/xarray.ufuncs.angle.html

2020-12-14 14:04 UTC, lanougue commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
I can not figure out a physical meaning of power_spectrum when density is set to False

2020-12-14 14:12 UTC, roxyboy commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
It just means that it isn't normalized by the spacing, i.e. `scaling='spectrum'` if you want to use scipy's convention.

2020-12-14 14:16 UTC, roxyboy commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
In order to not break the behavior, I vote for not changing this flag in this release. If we decide to change the flag to `scaling`, we would need to make both cases compatible, namely `scaling` and `density` flags and put a deprecation warning when `density` is called. `density=True` would be implemented as `scaling=density` and `density=False` would be implemented as `scaling=spectrum`.

2020-12-14 14:20 UTC, roxyboy commented
> I beleive that almost no one was using the density flag set to False. Can we just had a warning about deprecated "density" flag when the user sets it to False? Setting scaling="density' as default and removing density flag will ensure default behaviour being the same across version.
> Moreover, having the possibility to set scaling = "spectrum" seems to be used since it is in scipy.signal.periodogram function.

We can do this but we would still need to keep the `density` flag fully functional for this release so as not to break the behavior. If you want to change the flag to `scaling`, we would need to add a deprecation warning for when `density=True` or `density=False` is called.

2020-12-14 15:30 UTC, lanougue commented
@roxyboy, I have one failing tests that I can not resolve and that I think I should not resolve. In test_cross_phase_2d() line 516->544:
da1 and da2 have "y" coordinates that are all filled with "1" value. The spacing thus vanish for this dimension ! Fourier Transform over this dimension should thus not be possible.
However, dft do not complain because the spacing is still constant ! I think we should remove "y" coordinates or at least change it.
Can I change this test (while keeping its purpose of course) ?

2020-12-14 15:32 UTC, roxyboy commented
> @roxyboy, I have one failing tests that I can not resolve and that I think I should not resolve. In test_cross_phase_2d() line 516->544:
> da1 and da2 have "y" coordinates that are all filled with "1" value. The spacing thus vanish for this dimension ! Fourier Transform over this dimension should thus not be possible.
> However, dft do not complain because the spacing is still constant ! I think we should remove "y" coordinates or at least change it.
> Can I change this test (while keeping its purpose of course) ?

Good call. I agree, just change it to `range(Ny)` or something like that.

2020-12-14 15:49 UTC, lanougue commented
I also remove the Raise ValueError for the cross_phase in multiple dimensions. I do not see reason why it should not exist

2020-12-14 15:55 UTC, roxyboy requested changes

2020-12-14 15:55 UTC, roxyboy commented on xrft/tests/test_xrft.py
> -            xrft.cross_phase(da1, da2, dim=["y", "x"])
We should add a test that checks for two-dimensional cross_phase as we do for 1D below.

2020-12-14 15:57 UTC, roxyboy commented on xrft/xrft.py
> -            # cs /= daft1["freq_" + i + "_spacing"]
Can you remove this commented out line?

2020-12-14 16:03 UTC, lanougue commented on xrft/xrft.py
> -            # cs /= daft1["freq_" + i + "_spacing"]
It is noted in red color in github report and with "-" sign on left side. It is already removed. Right ?

2020-12-14 16:04 UTC, roxyboy commented on xrft/xrft.py
> -            # cs /= daft1["freq_" + i + "_spacing"]
Oh right, sorry got confused...

2020-12-14 16:11 UTC, lanougue commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
density = True corresponds to scaling='density' BUT density=False does NOT corresponds to scaling='spectrum'.
I think that in the actual behaviour density = False do not correspond to any physical quantity. However, scaling='spectrum" does.
This is why I suggest to simply abandon density=False and add scaling="spectrum" possibility.
It also match with scipy periodogram and other spectra calculation.

I agree that it will break density=False behaviour but isn't it useless ? A deprecation warninng and maybe a suggestion to evaluate it from the output of density=True output could be a solution ?

2020-12-14 19:30 UTC, roxyboy commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
Sorry, but breaking the behavior is a no go. If the `density=False` flag is bothering you, I'd recommend keeping the flag fully functional but with a deprecation flag and add the `scaling` flag in addition.

2020-12-14 20:12 UTC, lanougue commented
@roxyboy , I have modified test_cross_phase_2d to match its name.
I added one more test: test_cross_phase_true_phase_2d . For two signals with same values but with lagged coordinates, the offset should be recovered with the true_phase set to True in cross_phase.
I also think this behaviour will have to be documented

2020-12-15 10:51 UTC, lanougue commented
@roxyboy : To follow your recommandations, I added the scaling parameter in power_spectrum and cross_spectrum. Default scaling='density' will thus corresponds to actual default density=True. Density='False' will also be maintened (with warning).
Full consistency will thus be kept across versions.
If density flag is defined, a warning will be raised in both cases saying that density flag will be deprecated.
I also added scaling='spectrum' possibility

2020-12-15 10:55 UTC, roxyboy requested changes

2020-12-15 10:55 UTC, roxyboy commented on xrft/xrft.py
> +    if "density" in kwargs:
Cool, thanks for adding this. Also, just another small typo: "not be maintained" in the warning msg.

2020-12-15 10:55 UTC, roxyboy commented on xrft/xrft.py
> +    else:  # Corresponds to density=False
I'm not sure if this else statement works. I think `scaling` needs to be set as None as default for this to work.

2020-12-15 10:58 UTC, roxyboy commented on xrft/xrft.py
> +    else:  # Corresponds to density=False
Or, `elif density == False` could be the argument.

2020-12-15 11:01 UTC, lanougue commented on xrft/xrft.py
> +    else:  # Corresponds to density=False
ok, I replaced it with a more robust version

2020-12-15 11:12 UTC, lanougue commented
If you think it is a good idea, we can continue to maintain the density=False capability by adding a possible value to scaling flag such as "false_density" (as done actually in this new commit)

2020-12-15 11:25 UTC, roxyboy commented
> If you think it is a good idea, we can continue to maintain the density=False capability by adding a possible value to scaling flag such as "false_density" (as done actually in this new commit)

It's not a matter of it being a good idea or not but rather a requirement to maintain all functionality with a deprecation cycle when maintaining a package. I get your point of `density=False` being useless (for us) but I have no idea who is using this `xrft` package and if a function is dropped without warning, some users may find that very troubling. As such, we need to maintain the `density=False` flag for this release. We can remove it in the next cycle.

2020-12-15 11:31 UTC, lanougue commented
Of course. My question was more on the maintainance on a long term purpose of density=False available result.
The question is : do we say it will disapear at some point in the future or do we say that if will be transformed in scaling='false_density' and be maintained.

2020-12-15 11:32 UTC, roxyboy requested changes

2020-12-15 11:32 UTC, roxyboy commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
An error message of "When density is set to True, scaling must be set to density." might be more helpful for the user. Also, we'd need to add a test for this ValueError.

2020-12-15 11:33 UTC, roxyboy commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
And also a test for `scaling=spectrum`

2020-12-15 11:35 UTC, roxyboy commented
> Of course. My question was more on the maintainance on a long term purpose of density=False available result.
> The question is : do we say it will disapear at some point in the future or do we say that if will be transformed in scaling='false_density' and be maintained.

I think we can say that it'll be deprecated (meaning it'll disappear) in future releases.

2020-12-15 11:37 UTC, lanougue commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
Ok for the test. However, the idea of the VelueError is to warn the user that he can not use both density flag and scaling flag. Your suggestion look like the contrary

2020-12-15 11:40 UTC, lanougue commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
Maybe something like: "scaling flag and density flag can not be set simultenaously" ?

2020-12-15 12:01 UTC, lanougue commented
I add the test and change the location of the raise ValueError in order to be raised whatever density flag is

2020-12-15 12:51 UTC, roxyboy commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
We should test a case where dft gives a ValueError when we would expect a ValueError. There are a few examples of this in test_xrft.py already so I'll try to refer the lines.

2020-12-15 12:52 UTC, roxyboy commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
And I think `density=True` with `scaling='density'` should work for users. The cases where a ValueError should be raised are `density=False` with `scaling='density'` or `density=True` with `scaling='spectrum'`

2020-12-15 12:53 UTC, roxyboy requested changes

2020-12-15 12:53 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
I think we should accept the case where they are both set at `density=True` with `scaling='spectrum'`

2020-12-15 12:57 UTC, roxyboy commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
As in [here](https://github.com/xgcm/xrft/blob/a42f6b261abc8ab49d0baae9c2afb0d34fdcd895/xrft/tests/test_xrft.py#L96), we need to check that the function actually raises a ValueError as expected.

2020-12-15 13:01 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
What is it suppose to mean ? density=True matches with scaling='density', not scaling='spectrum'

2020-12-15 13:06 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
In fact, the code as it is now, accepts setting both density =True and scaling="density". Which is what you want, right ?

2020-12-15 13:22 UTC, lanougue commented on xrft/xrft.py
> +                raise ValueError("Both scaling and density can not be defined")
As the code is now:
`density = True` with `scaling='density'` works.
`density = True` with `scaling='spectrum'` raise a ValueError
`density = False` with `scaling='spectrum'` raise a ValueError
`density = False` with `scaling='density'` only raise a Warning saying that scaling flag is ignored. I made it like this because scaling is set to "density" as default. Thus, setting `density = False` would always raise a ValueError even if scaling is not defined by the user.

I think that keeping it like this is acceptable and maintain a default power_spectrum behaviour between version. What do you think ?

A test is already added between line 571 and 575 in test_xrft

2020-12-15 13:56 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
> In fact, the code as it is now, accepts setting both density =True and scaling="density". Which is what you want, right ?

Yes :) But the Value Error could be interpreted by the user as this won't work as `density=True` and `scaling='density'` is also setting the flags simultaneously.

2020-12-15 14:01 UTC, roxyboy requested changes

2020-12-15 14:01 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
Great, thanks for adding this test. Could you also add a case for `density=False` and `scaling='density'`?

2020-12-15 14:05 UTC, lanougue commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
In this condition, only a warning will be raised. Should we test for a warning ?

2020-12-15 14:06 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
Ah ok, no need for testing the warning then.

2020-12-15 14:07 UTC, lanougue commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
Ok, it think it should raise an error too. I will correct that

2020-12-15 14:08 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
Can you add the case for `density=False` and `scaling='spectrum'`?

2020-12-15 14:10 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
Actually, since the default is not going to be set as `scaling='density'`, I think the case of `densitt=False` and `scaling='density'` should only be a warning and not an error.

2020-12-15 14:11 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
I like your original idea of when `density=False`, the `scaling` flag being ignored.

2020-12-15 14:16 UTC, lanougue commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=True)
Ok, so let's go for that. I just add the other test for the raised error

2020-12-15 15:19 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=density)
This tests for raising a ValueError when `density=False` but... it should only raise a warning because `scaling` will be ignored right?

2020-12-15 15:50 UTC, lanougue commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=density)
The warning is raised only when `scaling = "density"`, not "spectrum". The test for ValueError is realized only with `scaling = "spectrum"`

2020-12-15 15:53 UTC, lanougue commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=density)
When `scaling="density"`, either density is et to True and the code works fine since everything is consistent, either density is set to False and the warning is raised

2020-12-15 16:02 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +            ps = xrft.power_spectrum(s, dim="x", scaling="spectrum", density=density)
Gotcha.

2020-12-15 16:09 UTC, roxyboy commented on xrft/xrft.py
> +                "Inverse Fourier Transform can not be computed because coordinate %s is not centered on zero frequency"
Sorry for nit picking. Do we have a test to check for this Value Error?

2020-12-15 16:13 UTC, lanougue commented on xrft/xrft.py
> +                "Inverse Fourier Transform can not be computed because coordinate %s is not centered on zero frequency"
Nope, I can make one.

I think that we aslo should have a ValueError when coordinates has values that all are the same. The returned error: division by zero (the spacing) is not really explicit.

2020-12-15 16:39 UTC, lanougue commented on xrft/xrft.py
> +                "Inverse Fourier Transform can not be computed because coordinate %s is not centered on zero frequency"
Both done

2020-12-15 16:49 UTC, lanougue commented
Even if there is no need of compatibility of idft with current xrft version, I just restore idft default behaviour with true_flags to False to be consistent with dft. (I set them to true in the commit before). I changed the message of the warning to be more explicit

2020-12-15 17:30 UTC, roxyboy commented on xrft/xrft.py
> +        msg = "Flags true_phase and true_amplitude will be set to True in future versions of xrft.idft to preserve the theoretical phasing and amplitude of IFT. Consider using xrft.ifft to ensure fut
Maybe we can spell out IFT as inverse FT to be user friendly?

2020-12-15 17:32 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Is this resolved? I just want to make sure so that the msg doesn't confuse the user.

2020-12-15 17:34 UTC, roxyboy commented
I think this is ready to merge. In hindsight, we probably should've split up this massive PR into multiple short PRs but "c'est la vie". @rabernat Can you give this PR a final approval?

2020-12-15 17:38 UTC, roxyboy commented
Thanks for you patience and all the work @lanougue !

2020-12-15 20:32 UTC, lanougue commented
Thank you too for reviewing all these modifications ! 

A last thing. In cross_phase, I set true_phase=False as default to keep the default behaviour across version
 In beleive that in future we should probably change it to true because it takes into account the coordinates to evaluate the correct cross_phase.
I think we should had a warning here too.

2020-12-15 20:38 UTC, roxyboy commented
> A last thing. In cross_phase, I set true_phase=False as default to keep the default behaviour across version
> In beleive that in future we should probably change it to true because it takes into account the coordinates to evaluate the correct cross_phase.
> I think we should had a warning here too.

I agree, a warning would be nice.

2020-12-15 21:01 UTC, lanougue commented
I added warnings for both cross_spectrum and cross_phase. All true_flags default behaviour is now only supported by dft and idft functions ensuring compatibility across all functions which depend on them.
Code looks more clear to me.

2020-12-15 21:06 UTC, roxyboy requested changes

2020-12-15 21:06 UTC, roxyboy commented on xrft/xrft.py
> +            + "Set explicitely true_phase = False in cross_phase arguments list to ensure future compatibility."
I'd add "future compatibility for numpy-like behavior where the coordinates are disregarded." As it stands, it sounds like setting the flag to False is better for future compatibility in general.

2020-12-15 21:06 UTC, roxyboy commented on xrft/xrft.py
> +            + "Set explicitely true_phase = False in cross_spectrum arguments list to ensure future compatibility."
Same point as below regarding "future compatibility".

2020-12-15 21:10 UTC, lanougue commented on xrft/xrft.py
> +            + "Set explicitely true_phase = False in cross_spectrum arguments list to ensure future compatibility."
I prefer "disregarded" to "discarded"

2020-12-15 21:11 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Also a small typo for "simultaneously."

2020-12-15 21:12 UTC, roxyboy commented on xrft/xrft.py
> +            + "Set explicitely true_phase = False in cross_spectrum arguments list to ensure future compatibility."
Sure, whichever works for me.

2020-12-15 21:14 UTC, lanougue commented on xrft/xrft.py
> +            + "Set explicitely true_phase = False in cross_phase arguments list to ensure future compatibility."
Much better indeed !

2020-12-15 21:17 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
How about "scaling cannot be set to 'spectrum' when density is defined."?

2020-12-15 21:24 UTC, lanougue commented
Loooong PR ! :) Happy that it reaches the end

2020-12-15 21:25 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
@lanougue Last fix please...

2020-12-15 21:31 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Actually, the code only accepts to set both scaling='density' and density='True' because they mean the same thing.
Other configuration with both defined should raise a ValueError.
For now, we only makes the exception of density=False and scaling="desnity" which only raise a warning saying that scaling is ignored

2020-12-15 21:32 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
I think the user should never be able to set both scaling and density since it leads to severe misunderstanding on what the code should return.

2020-12-15 21:33 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Ok, but my initial claim still holds. The Error message as it stands states that it won't accept the case of scaling='density' and density=True either.

2020-12-15 21:35 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
In essence, we're only returning a ValueError when `density` is called no matter it be True or False when `scaling='spectrum'`

2020-12-15 21:35 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
So, we should make the error message match this.

2020-12-15 21:36 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Yes. As it, even if the error message claims that, it still  work because 1) We allow it 2) they are equivalent.
What do you suggest ?

2020-12-15 21:37 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
I recommend the error to be: "scaling cannot be set to 'spectrum' when density is called." as this is what what's actually happening.

2020-12-15 21:39 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
*when the density flag is called.

2020-12-15 21:40 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
I suggest that, for clarity, an error should always be raised if both flags are defined, no matter their value.

2020-12-15 21:42 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
If we do this, we'd need to set the default of scaling to None as setting scaling='density' as the default would always raise an error when the density flag is called and this would break the behavior. So I do not agree with this.

2020-12-15 21:45 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
You are right. But I am sure I can find a workaround to have the default scaling to density without raising the error. I just need to check if the user set it explicitely or not in the argument list

2020-12-15 21:49 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
What you're proposing sounds like a lot of extra `if` statements for a feature that'll be deprecated in future cycles. I'm not sure why you're so against just clarifying the error message of what it's doing...

2020-12-15 21:50 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
We already have in the warning message above a more detailed explanation whenever the density flag is called.

2020-12-15 21:52 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
I do not really like it because it sounds that in some cases we are allowed to set both flags and sometime we are not allowed, depending on their values. Which is strange for me.
I prefer to make the user choose one of the two flags

2020-12-15 21:53 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Having both flags set simultaneously would mean that the user do not know how to choose them

2020-12-15 21:57 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Do I give a try ? It will gain in clarity with simple error message I think

2020-12-15 21:58 UTC, roxyboy commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Ok, you seem willing to try it so, why not.

2020-12-15 22:24 UTC, roxyboy commented on xrft/xrft.py
> +    if "scaling" in kwargs:
The problem with hiding `scaling` in kwargs in my opinion is that the user will have a hard time knowing that the flag even exists as it's not in xrft.dft...

2020-12-15 22:24 UTC, lanougue commented on xrft/xrft.py
> +                "scaling flag and density flag can not be set simultenaously"
Sorry for being a bit stubborn, but I think it is more clear for a user point of view.
code is even shorter ! :)

2020-12-15 22:27 UTC, roxyboy commented on xrft/xrft.py
> +    if "scaling" in kwargs:
If we're going to relegate `scaling` to kwargs, we need to add more explanation to the docstring of the function to explain what it takes in addition to kwargs accepted in xrft.dft

2020-12-15 22:28 UTC, lanougue commented on xrft/xrft.py
> +    if "scaling" in kwargs:
Yes, I agree. It is in the description of the argument list, but I do not know another way.
Do we have another way to check if the user set an argument explicitely or if it is the default value ?

2020-12-15 22:31 UTC, lanougue commented on xrft/xrft.py
> +    if "scaling" in kwargs:
Maybe some hope with that:
https://stackoverflow.com/questions/14749328/how-to-check-whether-optional-function-parameter-is-set

2020-12-15 22:36 UTC, roxyboy requested changes

2020-12-15 22:36 UTC, roxyboy commented on xrft/xrft.py
>      kwargs : dict : see xrft.dft for argument list
I think we should list the possible keyword arguments that are not in xrft.dft as they do [here](https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs-kwargs)

2020-12-15 22:37 UTC, roxyboy commented on xrft/xrft.py
>      kwargs : dict : see xrft.dft for argument list
So the list should have `scaling` and `density`.

2020-12-15 22:40 UTC, lanougue commented on xrft/xrft.py
>      kwargs : dict : see xrft.dft for argument list
Ok, Following you link recommandations, `dim` should also appear because it is always used

2020-12-15 22:41 UTC, roxyboy commented on xrft/xrft.py
>      kwargs : dict : see xrft.dft for argument list
Agreed.

2020-12-15 23:04 UTC, lanougue commented on xrft/xrft.py
>      kwargs : dict : see xrft.dft for argument list
I agree that function signature is important. I 'll try to find a way

2020-12-15 23:27 UTC, lanougue commented on xrft/xrft.py
>      kwargs : dict : see xrft.dft for argument list
What do you think about this solution:

We keep `scaling=True` in the signature of the function. It define its default behaviour (which continue the same as the actual version).
'density' flag stays in kwargs for two reasons:
1) it will be deprecated
2) This will not encourage new user to use it

If density is still manually set by the user (easily detectable since it is in the kwargs), we raise a warning saying that scaling flag is simply ignored.
This warning thus occurs when density if defined by the user and whatever density and scaling values are. This ensure compatibility and smooth transition.

I think it fullfil all our needs

2020-12-16 06:18 UTC, roxyboy commented on xrft/xrft.py
> +        msg = "scaling flag is ignored !"
Can we just combine this warning with the one above?

2020-12-16 06:18 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +    # @pytest.mark.parametrize("density", [False, True])
Can you remove the commented out lines?

2021-01-05 15:49 UTC, lanougue commented
Happy new year 2021. May xrft have a long life !
@roxyboy , @rabernat . What about this PR ? followed by a new release ?

2021-01-28 16:16 UTC, rabernat commented on xrft/xrft.py
> +    if "scaling" in kwargs:
Has this issue been resolved?

2021-01-28 16:16 UTC, rabernat commented
Sorry @lanougue we have neglected your PR for so long. From my point of view, everything looks good to merge.

@roxyboy do you agree?

2021-01-28 16:35 UTC, rabernat commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
I support the idea of deprecating the `density=False` option and moving towards the `scaling` parameter. But we need to do this via a deprecation cycle. That is what appears to be implemented now.

2021-01-28 16:42 UTC, lanougue commented on xrft/xrft.py
> +    if "scaling" in kwargs:
I think so. "scaling" now appears in argument list as expected. If the user keep using "density", it will work but will raise a deprecation warning

2021-01-28 16:49 UTC, lanougue commented on xrft/xrft.py
> +        fs = np.prod([float(ps[d].spacing) for d in updated_dims])
Yes, this is what now appears in the last version of the PR

2021-01-28 17:06 UTC, roxyboy commented
@rabernat Yes, I agree with merging this PR :)

2021-01-28 17:06 UTC, merged