More examples for documentation
xgcm/xrft pull request #135
Opened 2021-01-30 21:30 UTC by roxyboy

I started a PR to have more examples for the documentation. This address issues #86 and #105 .

2021-01-30 21:55 UTC, roxyboy commented
Not sure why the tests are failing in Python 3.8...

2021-01-31 00:05 UTC, navidcy commented
I can't open the ReviewNB. I think only repo contributors can do that?

2021-01-31 00:08 UTC, navidcy commented
Python 3.8 fails [here](https://github.com/xgcm/xrft/pull/135/checks?check_run_id=1798840909#step:6:51)
But why 3.7 does not fail at the same point I don't know...

2021-01-31 09:44 UTC, roxyboy commented
> Python 3.8 seems fails [here](https://github.com/xgcm/xrft/pull/135/checks?check_run_id=1798840909#step:6:51)

@lanougue Do you have any ideas on why it's failing when `true_phase=True`?

2021-01-31 09:57 UTC, roxyboy commented
> I can't open the ReviewNB. I think only repo contributors can do that?

@navidcy I think you have to link your Github account to ReviewNB because it's a third-party app?

2021-01-31 10:03 UTC, roxyboy commented
The test are now all passing without me touching anything but the example notebooks... weird

2021-01-31 19:30 UTC, navidcy commented
> > I can't open the ReviewNB. I think only repo contributors can do that?
> 
> 
> 
> @navidcy I think you have to link your Github account to ReviewNB because it's a third-party app?

I did that but still I can only see the repos I have write access on.

2021-01-31 19:57 UTC, roxyboy commented
> > > I can't open the ReviewNB. I think only repo contributors can do that?
> > 
> > 
> > @navidcy I think you have to link your Github account to ReviewNB because it's a third-party app?
> 
> I did that but still I can only see the repos I have write access on.

That's inconvenient... It's my first time to use ReviewNB so I'm not quite sure how to change the settings. Do you think adding you as a maintainer would change this @navidcy ?

2021-01-31 20:57 UTC, navidcy commented
> > > > I can't open the ReviewNB. I think only repo contributors can do that?
> 
> > > 
> 
> > > 
> 
> > > @navidcy I think you have to link your Github account to ReviewNB because it's a third-party app?
> 
> > 
> 
> > I did that but still I can only see the repos I have write access on.
> 
> 
> 
> That's inconvenient... It's my first time to use ReviewNB so I'm not quite sure how to change the settings. Do you think adding you as a maintainer would change this @navidcy ?

I can just view the notebook by itself, no?

2021-01-31 20:58 UTC, navidcy commented
> The tests are now all passing without me touching anything but the example notebooks... weird

Do the tests use random numbers and if so, do you prescribe the random seed?

2021-01-31 21:00 UTC, roxyboy commented
> > > > > I can't open the ReviewNB. I think only repo contributors can do that?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > @navidcy I think you have to link your Github account to ReviewNB because it's a third-party app?
> > 
> > 
> > > 
> > 
> > 
> > > I did that but still I can only see the repos I have write access on.
> > 
> > 
> > That's inconvenient... It's my first time to use ReviewNB so I'm not quite sure how to change the settings. Do you think adding you as a maintainer would change this @navidcy ?
> 
> I can just view the notebook by itself, no?

Yep, you can if that works for you.

2021-01-31 21:01 UTC, roxyboy commented
> > The tests are now all passing without me touching anything but the example notebooks... weird
> 
> Do the tests use random numbers and if so, do you prescribe the random seed?

I don't think so?

2021-02-01 12:35 UTC, lanougue commented
Weird fail indeed. If it happens again, I can give a deeper look

2021-02-03 20:23 UTC, navidcy commented
@roxyboy, these notebooks will be compiled by the docs somehow or they will be just there in `doc` folder for users to open and explore? If the former, how can I compile/view the docs locally?

2021-02-03 20:28 UTC, navidcy commented
I think I managed to open the notebook from the ReviewNB after all ;)

2021-02-03 20:39 UTC, navidcy requested changes

2021-02-03 20:39 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +    "x0 = np.diff(x)[0]*nx \n",
why not simply `x0 = dx * nx`?

2021-02-03 20:39 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +    "nx = 70                          # defining a shift\n",
`nx` is not verbose enough... one may think that this is the total number of points in `x`. How about `nshift`?

2021-02-03 20:39 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA1gAAAI4CAYAAAB3HEhGAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8
well retreived --> retrieved

2021-02-03 20:39 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA1gAAAI4CAYAAAB3HEhGAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8
I feel that we should make the default behavior returning the compensated spectra and delete this part of the notebook. (Sorry if this was already discussed in a recent PR and I missed it.)

Also:
scipy-like --> `scipy`-like

2021-02-03 20:39 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +{
<p>I think a few more sentences here are needed explaining what's the main thing this notebook means to demonstrate.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2021-02-03 20:39 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +{
<p>add <code>;</code> after <code>ax.set_xlim([-8,8])</code> to avoid the <code>(-8, 8)</code> output.</p><p>(same before all plots below)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-02-03 20:39 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +{
<p>This part of the notebook seems a bit out of context.</p><p>Also, I'd urge to change the default behavior for real fft and then spare ourselves from this section all together.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2021-02-03 20:52 UTC, roxyboy commented
> @roxyboy, these notebooks will be compiled by the docs somehow or they will be just there in `doc` folder for users to open and explore? If the former, how can I compile/view the docs locally?

They will be compiled (nicely).

2021-02-04 10:23 UTC, roxyboy commented on doc/DFT-iDFT_example.ipynb
> +{
Well, if so this should be done in another PR.

2021-02-06 16:57 UTC, roxyboy commented on doc/DFT-iDFT_example.ipynb
> +{
I made a PR #136 to change the behavior of real FFT.

2021-02-06 17:01 UTC, roxyboy commented on doc/DFT-iDFT_example.ipynb
> +    "x0 = np.diff(x)[0]*nx \n",
Done.

2021-02-07 02:16 UTC, navidcy commented
> > @roxyboy, these notebooks will be compiled by the docs somehow or they will be just there in `doc` folder for users to open and explore? If the former, how can I compile/view the docs locally?
> 
> They will be compiled (nicely).

How can I compile locally to have a look?

2021-02-07 02:22 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +{
<ul><li>In this notebook...</li><li>harnesses the data array's metadata</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2021-02-07 02:22 UTC, navidcy commented on doc/DFT-iDFT_example.ipynb
> +{
<ul><li>By using <code>xrft.idft</code>  along... <code>true_amplitude=True</code>  the informations regarding shifted coordinates is automatically taken into consideration.</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2021-02-07 02:25 UTC, navidcy commented on doc/Parseval_example.ipynb
> +{
<ul><li>"First, we demonstrate Parseval's theorem for one-dimensional data."</li><li>I'm wondering whether it's clearer to state Parseval's theorem with integrals, perhaps even before the sentence above. And then for each case note that the integral expressions are approximated by the sums already written down. @roxyboy, what do you think?</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2021-02-07 02:25 UTC, navidcy commented on doc/Parseval_example.ipynb
> +{
<p>"Now, we demonstrate Parseval's theorem for two-dimensional data."</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-02-07 06:50 UTC, roxyboy commented on doc/Parseval_example.ipynb
> +{
Depending on PR #136 , we may no longer be able to present the Parseval's theorem as an example as the amplitude correction does not guarantee Parseval's any more.

2021-02-10 16:45 UTC, cspencerjones commented on doc/DFT-iDFT_example.ipynb
> +{
<p>With the relevant flags, <code>xrft</code>'s  <code>dft</code>   can preserve information about the data's location in its original space. This information is not preserved in a numpy fourier transform. This section demonstrates how to preserve this information using the <code>true_phase=True, true_amplitude=True</code>  flags. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2021-02-10 16:46 UTC, cspencerjones commented on doc/DFT-iDFT_example.ipynb
> +{
<p>Urrgh I haven't figured out NB review - basically I'd like to add the above comment to the text here. </p>

2021-02-10 16:51 UTC, cspencerjones commented on doc/Parseval_example.ipynb
> +{
<p>A couple of comments saying what you are actually doing would be helpful!</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2021-02-10 16:51 UTC, cspencerjones commented on doc/Parseval_example.ipynb
> +{
<p>Comments here would also be nice.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/xgcm/xrft/pull/135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2021-02-11 13:18 UTC, cspencerjones commented on doc/Parseval_example.ipynb
> +{
I've been thinking about this - even if you can't get these assertions to be `True` (or if you have to use some specific flags to make it work), it's important to give some version of Parseval's theorem to help people understand the relationship between their units in physical space and their units in spectral space. So I hope we can keep the main idea here.

2021-02-11 20:08 UTC, dougiesquire commented on doc/Parseval_example.ipynb
> +{
I agree. I hope that #136 will clarify things, not confuse them. 

I suspect that some of the ongoing confusion has come from the previous inability to produce a psd that integrated (even approximately) to the energy of the input signal when a `real` dim was provided or `window=True`. This certainly confused me when I first started using xrft.

I'm happy to have a stab at writing some documentation about the new flags and when, how, and how much one can expect to satisfy Parsevals. That is, if I can work out how to use ReviewNB...

2021-02-18 13:20 UTC, roxyboy commented
I'm gonna close this and start a new PR because there are quite a few new features that got merged after I started this.

2021-02-18 13:20 UTC, closed without merging

2021-02-18 14:40 UTC, roxyboy commented
I opened PR #140