Making real FFT convention similar to scipy
xgcm/xrft pull request #136
Opened 2021-02-06 16:56 UTC by roxyboy

A PR to double the power and cross spectrum when `real` is called in order to adhere with `scipy.signal.periodogram(return_onesided=True)` convention. This addresses issue #105 .

2021-02-06 21:48 UTC, roxyboy commented
I added a flag `correct_amplitude` to account for the amplitude diminishment due to windowing but when you correct for this, the Parseval's identity is no longer satisfied. Maybe @dougiesquire can comment more on this.
I think this has to due to the windowing putting more weighting on lower wavenumbers when the spectrum is not white (because windowing in the spatial domain translates to a convolution in the wavenumber domain) so simply multiplying the mean of the window to the spectra doesn't become equivalent to the variance of original data.

2021-02-06 21:52 UTC, roxyboy commented on xrft/xrft.py
> +                windows, _ = _apply_window(da, dim)
@dougiesquire I think I'm doing this correctly but can you double check?

2021-02-06 21:54 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +    #     da_corrected = (da_prime * window) ** 2 / np.mean(np.hanning(N / n_segments)**2)
@dougiesquire This is where I try to assert the Parseval's identity when correcting for the amplitude change due to windowing. I have commented out for now because I couldn't make it work.

2021-02-06 21:54 UTC, roxyboy commented on xrft/tests/test_xrft.py
> +        # da_corrected.mean(dim).values,
@dougiesquire When corrected, I think this should assert for `da_corrected`...

2021-02-07 01:36 UTC, dougiesquire reviewed
FYI, I'm going to wait until we've resolved discussions on #104 before reviewing this properly. Just noticed this minor issue while trying to re-familiarise myself with our tests.

2021-02-07 01:37 UTC, navidcy commented
@roxyboy I don't agree with having a kwarg "correct_amplitude=True". The amplitude should be corrected always without the user needing to specifically ask for it. Who would like to be returned with the wrong amplitude? Am I missing anything?

2021-02-07 01:39 UTC, dougiesquire commented
> @roxyboy I don't agree with having a kwarg eg "correct_amplitude=True". The amplitude should be corrected always without the user needing to specifically ask for it. Who would like to be returned with the wrong amplitude? Am I missing anything?

I agree with this. This is not an option in `scipy`, the correction is just done.

2021-02-07 01:48 UTC, dougiesquire commented
The only fiddly thing is that Parseval's may only be approximately satisfied when non-uniform windowing is applied and corrected for. So how to robustly test Parseval's theorem? Is it sufficient to test that we get the same result as `scipy` (see also https://github.com/xgcm/xrft/issues/104#issuecomment-774572393)?

2021-02-07 02:05 UTC, navidcy commented
> > @roxyboy I don't agree with having a kwarg eg "correct_amplitude=True". The amplitude should be corrected always without the user needing to specifically ask for it. Who would like to be returned with the wrong amplitude? Am I missing anything?
> 
> I agree with this. This is not an option in `scipy`, the correction is just done.
> 
> It's also not strictly the amplitude that we are correcting for, but the energy - see https://community.sw.siemens.com/s/article/window-correction-factors.

Continuing this thread: what does the `idft()` function expect then `real=True`? Does it expect to get a data array with the *correct* amplitude or with the *wrong/halved* amplitude? It should be the former, right?

2021-02-07 02:29 UTC, dougiesquire commented
> > > @roxyboy I don't agree with having a kwarg eg "correct_amplitude=True". The amplitude should be corrected always without the user needing to specifically ask for it. Who would like to be returned with the wrong amplitude? Am I missing anything?
> > 
> > 
> > I agree with this. This is not an option in `scipy`, the correction is just done.
> > It's also not strictly the amplitude that we are correcting for, but the energy - see https://community.sw.siemens.com/s/article/window-correction-factors.
> 
> Continuing this thread: what does the `idft()` function expect then `real=True`? Does it expect to get a data array with the _correct_ amplitude or with the _wrong/halved_ amplitude? It should be the former, right?

Sorry, I think we could be talking about two different issues that are being addressed in this PR:
1. Using a `real` dimension returns a one-sided spectrum that has not had its energy compensated for being one-sided and so integrates to only half of the signal energy (#105).
2. Applying non-uniform weighting reduces the energy in a signal and we currently don't correct for this (#104).

Regarding 1., I think the correction (essentially a multiplication by 2) should happen by default. But this should only be applied within the `*_spectrum` functions. `dft()` and `idft()` need not be modified.

Regarding 2., I also think the correction (scaling by the energy of the window) should happen by default. But we need to think about how to test this as this correction may only approximately satisfy Parseval's theorem (still better than not correcting, which will significantly underestimate energy).

2021-02-07 06:46 UTC, roxyboy commented
When starting off when spectrum, one of the first things a user usually tests is to see if one is doing it correctly is to see whether the Parseval's identity is satisfied. Therefore, I find the correction only approximately satisfying the Parseval's identity quite troubling...

2021-02-07 06:47 UTC, roxyboy commented
> Regarding 1., I think the correction (essentially a multiplication by 2) should happen by default. But this should only be applied within the `*_spectrum` functions. `dft()` and `idft()` need not be modified.

This is already done in this PR.

2021-02-07 07:02 UTC, roxyboy commented
> I therefore, vote for keeping the default behavior as not correcting for the amplitude and returning an output that satisfies Parseval's exactly.

In the current version of `xrft`, the Parseval's identity is satisfied exactly for the spatial variance of the windowed data. https://github.com/xgcm/xrft/blob/7381a801edb3605db123dbfffde840a1f2097df4/xrft/tests/test_xrft.py#L633

2021-02-07 08:23 UTC, dougiesquire commented
> > Regarding 2., I also think the correction (scaling by the energy of the window) should happen by default. But we need to think about how to test this as this correction may only approximately satisfy Parseval's theorem (still better than not correcting, which will significantly underestimate energy).
> 
> When starting off when spectrum, one of the first things a user (and also I) usually test is to see if one is doing it correctly is to check whether the Parseval's identity is satisfied. Therefore, I find the correction only approximately satisfying the Parseval's identity quite troubling...
> I therefore, vote for keeping the default behavior as not correcting for the amplitude and returning an output that satisfies Parseval's exactly.

I disagree. The test that you're referring to as "satisfying Parseval's exactly" actually tests that the integral of the windowed spectrum matches the energy of the _windowed_ signal. I don't think this is a very meaningful test. I think that most users will expect to be able to calculate the psd/csd and interpret the magnitude of the output in the same way regardless of the windowing applied - that is, as an indication of the power as a function of frequency. That is not the current behaviour. Right now, the magnitude of a spectrum is substantially attenuated if `window=True`.

Just to be clear, `scipy` spectral functions apply this correction - there's not even an option to not apply it.

2021-02-07 08:24 UTC, roxyboy commented
> Just to be clear, `scipy` spectral functions apply this correction - there's not even an option to not apply it.

Right, and I would probably be confused as to why `scipy` didn't satisfy the Parseval's identity if it were have not been for this discussion.

2021-02-07 08:26 UTC, roxyboy commented
And I'm not sure what you mean by it not being a meaningful test... Based on Parseval's theorem, `the integral of the windowed spectrum matches the energy of the windowed signal` is indeed what should happen. It's one of the fundamental justifications why one can use spectrum as a method to decompose the energy into wavenumber modes.

2021-02-07 08:48 UTC, dougiesquire commented
> And I'm not sure what you mean by it not being a meaningful test... Based on Parseval's theorem, `the integral of the windowed spectrum matches the energy of the windowed signal` is indeed what should happen. It's one of the fundamental justifications why one can use spectrum as a method to decompose the energy into wavenumber modes.

I agree that this test must pass if one hasn't corrected for the energy reduction due to windowing. But I personally don't think an uncorrected spectra is very useful. The window is only there to help reduce leakage during the FFT so I think its influence on the power should be accounted for. I'm not sure why anyone would want to compute a power spectrum that doesn't give a direct indication of the power in the input signal.

The whole point in the correction is so that Parseval's theorem is (approximately) satisfied. Without the correction, the integral of a windowed spectrum is reduced relative to the energy of the input signal. This isn't a great webpage, but it might be useful: https://community.sw.siemens.com/s/article/window-correction-factors.

2021-02-07 17:04 UTC, roxyboy commented
> I agree that this test must pass if one hasn't corrected for the energy reduction due to windowing. But I personally don't think an uncorrected spectra is very useful. The window is only there to help reduce leakage during the FFT so I think its influence on the power should be accounted for. I'm not sure why anyone would want to compute a power spectrum that doesn't give a direct indication of the power in the input signal.

I can only speak for my personal experience but I was only interested in the spectral slopes and seasonal change in the energy and not the absolute energy itself so for me, the windowed data satisfying the Parseval's theorem was the priority. But I also see your point so that is why I think having the option as the `boost_amplitude` is the best way to go.

2021-02-07 21:36 UTC, dougiesquire commented
> But I also see your point so that is why I think having the option as the `boost_amplitude` is the best way to go.

What about `correct_energy`? Whatever you decide, as always, clear documentation is probably what's really crucial. Let me know if/how I can help out with this.

2021-02-08 13:56 UTC, lanougue commented
@roxyboy Just a comment here. I might be wrong but you multiplied by 2 the *_spectrum() outputs when a "real" is in args. However, first value (null frequency) and last value (highest frequency) should not be multriplied by two. (Same in scipy). See first figure of @105.
I think that line cs = cs * 2 and ps = ps*2 should be complemented by something like:
```
cs[{real:0}] = 0.5*a[{real:0}]
cs[{real:-1}] = 0.5*a[{real:-1}]
```

2021-02-08 14:40 UTC, lanougue commented on xrft/tests/test_xrft.py
> +        npt.assert_almost_equal(ps.values[1:-1], p_scipy[1:-1])
First and last values should match too between scipy and xrft.power_spectrum.
These two values should not be multiplied by 2 in xrft.power_spectrum. See my comment in the current discussion

2021-02-08 14:41 UTC, rabernat commented
> I think that line cs = cs * 2 and ps = ps*2 should be complemented by something like:
> 
> ```
> cs[{real:0}] = 0.5*a[{real:0}]
> cs[{real:-1}] = 0.5*a[{real:-1}]
> ```

This will not work for dask-backed arrays because you can't assign to them. So we would need a lazy version of this function.

2021-02-08 14:44 UTC, lanougue commented
The expected behaviour of returning single sided spectrum is to discard redundant information. Null and highest frequencies are NOT duplicated in two-sided spectrum. Thus, they should not be doubled. However, all the other frequencies are duplicated. They just can be safely discarded (and doubled if we choose scipy convention)

2021-02-08 14:50 UTC, lanougue commented
> > I think that line cs = cs * 2 and ps = ps*2 should be complemented by something like:
> > ```
> > cs[{real:0}] = 0.5*a[{real:0}]
> > cs[{real:-1}] = 0.5*a[{real:-1}]
> > ```
> 
> This will not work for dask-backed arrays because you can't assign to them. So we would need a lazy version of this function.

Ok, I suggest to remove cs = cs * 2 and do:
```
f = np.full(cs.sizes[real], 2., dtype=cs.dtype)
f[0],f[-1]=1.,1.
cs = cs * xr.DataArray(f, dims='x')
```

2021-02-08 21:19 UTC, roxyboy commented
> Ok, I suggest to remove cs = cs * 2 and do:
> 
> ```
> f = np.full(cs.sizes[real], 2.)
> f[0],f[-1]=1.,1.
> cs = cs * xr.DataArray(f, dims=real)
> ```

Done :)

2021-02-08 21:20 UTC, roxyboy commented
> What about `correct_energy`? Whatever you decide, as always, clear documentation is probably what's really crucial. Let me know if/how I can help out with this.

Cross spectrum isn't really "energy" so I think `boost_amplitude` is better...

2021-02-08 22:06 UTC, lanougue commented on xrft/xrft.py
> +            ps = ps * xr.DataArray(f, dims="freq_" + kwargs[arg])
I would code:
```
real_dim =[d for d in updated_dims if real==d[-len(real):]][0] # find transformed real dimension
f = np.full(ps.sizes[real_dim], 2.0)
f[0], f[-1] = 1.0, 1.0
ps = ps * xr.DataArray(f, dims=real_dim)
```

2021-02-08 22:23 UTC, dougiesquire commented
> > > I think that line cs = cs * 2 and ps = ps*2 should be complemented by something like:
> > > ```
> > > cs[{real:0}] = 0.5*a[{real:0}]
> > > cs[{real:-1}] = 0.5*a[{real:-1}]
> > > ```
> > 
> > 
> > This will not work for dask-backed arrays because you can't assign to them. So we would need a lazy version of this function.
> 
> Ok, I suggest to remove cs = cs * 2 and do:
> 
> ```
> f = np.full(cs.sizes[real], 2.)
> f[0],f[-1]=1.,1.
> cs = cs * xr.DataArray(f, dims=real)
> ```

I think the behaviour depends on whether the number of points is even or odd (see [numpy.fft.rfft](https://numpy.org/doc/stable/reference/generated/numpy.fft.rfft.html))
For even inputs, we would want something like what @lanougue has above, but for odd inputs, I don't think the last (highest) frequency should be replaced with 1., e.g.
```
f = np.full(cs.sizes[real], 2.)
f[0]=1.
cs = cs * xr.DataArray(f, dims=real)
```

2021-02-08 22:31 UTC, navidcy commented
> > > > I think that line cs = cs * 2 and ps = ps*2 should be complemented by something like:
> > > > ```
> > > > cs[{real:0}] = 0.5*a[{real:0}]
> > > > cs[{real:-1}] = 0.5*a[{real:-1}]
> > > > ```
> > > 
> > > 
> > > This will not work for dask-backed arrays because you can't assign to them. So we would need a lazy version of this function.
> > 
> > 
> > Ok, I suggest to remove cs = cs * 2 and do:
> > ```
> > f = np.full(cs.sizes[real], 2.)
> > f[0],f[-1]=1.,1.
> > cs = cs * xr.DataArray(f, dims=real)
> > ```
> 
> I think the behaviour depends on whether the number of points is even or odd (see [numpy.fft.rfft](https://numpy.org/doc/stable/reference/generated/numpy.fft.rfft.html))
> For even inputs, we would want something like what @lanougue has above, but for odd inputs, I don't think the last (highest) frequency should be replaced with 1., e.g.
> 
> ```
> f = np.full(cs.sizes[real], 2.)
> f[0]=1.
> cs = cs * xr.DataArray(f, dims=real)
> ```

Nice catch! (In an ideal world, a test with odd number of points should have raised a red flag. :) )

2021-02-08 22:32 UTC, lanougue commented
@roxyboy 
real flag is finally quite important in how power_spectrum() behave. I think it could be added in the signature of the function.
It would also avoid all kwargs[arg] everywhere.
I would suggest to just adding
`if real is not None:...`

2021-02-08 22:32 UTC, navidcy commented on xrft/tests/test_xrft.py
> +        # window = np.hanning(N) * np.hanning(N)[:, np.newaxis]
remove commented code?

2021-02-08 22:33 UTC, navidcy commented on xrft/xrft.py
> +        transform is taken. Please adhere to scipy.signal.windows' naming convention.
suggest: Please adhere to `scipy.signal.windows` for naming convention.

2021-02-08 22:34 UTC, navidcy commented on xrft/xrft.py
> +        transform is taken. Please adhere to scipy.signal.windows' naming convention.
same here; I suggest: Please adhere to scipy.signal.windows for naming convention.

2021-02-08 22:34 UTC, navidcy requested changes
Some very minor suggestions..

2021-02-08 23:09 UTC, dougiesquire commented
> Cross spectrum isn't really "energy" so I think `boost_amplitude` is better...

My only concern with having "amplitude" in the name is that there is a _different_ correction that specifically corrects the amplitude of the spectrum (rather than its integral/energy). So I worry that `boost_amplitude` could be confusing for users.

2021-02-08 23:15 UTC, lanougue commented
It could be easy to change window ampltude in order to have the windowed signal to have the same energy (variance) as the original signal. Thus, paserval will be perfectly respected in both cases (windowed and not windowed).
The user will thus have no need to worry about it

2021-02-08 23:18 UTC, roxyboy commented
> It could be easy to change window ampltude in order to have the windowed signal to have the same energy (variance) as the original signal. Thus, paserval will be perfectly respected in both cases (windowed and not windowed).
> The user will thus have no need to worry about it

I'm not sure how to do this consistently. Do you have example code?

2021-02-08 23:19 UTC, lanougue commented
> > It could be easy to change window ampltude in order to have the windowed signal to have the same energy (variance) as the original signal. Thus, paserval will be perfectly respected in both cases (windowed and not windowed).
> > The user will thus have no need to worry about it
> 
> I'm not sure how to do this consistently. Do you have example code?

I edited my comment to explain. What do you think ?

2021-02-08 23:45 UTC, dougiesquire commented
> > > It could be easy to change window ampltude in order to have the windowed signal to have the same energy (variance) as the original signal. Thus, paserval will be perfectly respected in both cases (windowed and not windowed).
> > > The user will thus have no need to worry about it
> > 
> > 
> > I'm not sure how to do this consistently. Do you have example code?
> 
> I edited my comment to explain. What do you think ?

Do you just mean to scale the windowed spectrum by the ratio of the windowed and non-windowed rms (rather than by the correction factor computed from the window) - i.e. enforce Parseval's?

2021-02-08 23:49 UTC, dougiesquire commented
> I edited my comment to explain. What do you think ?

Sure we could do this. In my very limited experience this is not commonly done but I don't know why not...

2021-02-09 01:04 UTC, dougiesquire commented
I've just noticed that `scipy` actually has a test for the window correction using a simple sinusoidal signal. `xrft` obviously also passes this test if the original correction I suggested is applied. Run-able code below.

```python
import xrft
import scipy.signal as sps
from numpy.testing import assert_allclose

# The following is copied from scipy test function test_window_correction() 
# see https://github.com/scipy/scipy/blob/master/scipy/signal/tests/test_spectral.py#L485
# 
# I've made a few minor edits so we can easily run the same test using xrft:
#   1. Added return_onesided=False
#   2. Added noverlap=0 
#   3. Test the 'Hann' window only
#   4. Commented out the tests of scaling='spectrum'

A = 20
fs = 1e4
nperseg = int(fs//10)
fsig = 300
ii = int(fsig*nperseg//fs)  # Freq index of fsig

tt = np.arange(fs)/fs
x = A*np.sin(2*np.pi*fsig*tt)

for window in ['hann']: #, 'bartlett', ('tukey', 0.1), 'flattop']:
    # _, p_spec = sps.welch(x, fs=fs, nperseg=nperseg, window=window, 
    #                       noverlap=0, return_onesided=False,
    #                       scaling='spectrum')
    freq, p_dens = sps.welch(x, fs=fs, nperseg=nperseg, window=window, 
                             noverlap=0, return_onesided=False,
                             scaling='density')

    # Check peak height at signal frequency for 'spectrum'
    # assert_allclose(p_spec[ii], A**2/2.0)
    # Check integrated spectrum RMS for 'density'
    assert_allclose(np.sqrt(np.trapz(p_dens, freq)), A*np.sqrt(2)/2,
                    rtol=1e-3)
```
And using `xrft`:
```python
x_da = xr.DataArray(x, coords=[tt], dims=['t']).chunk({'t': nperseg})

p_xrft = xrft.xrft.power_spectrum(x_da, 
                                  dim=['t'],
                                  window=True,
                                  chunks_to_segments=True).mean('t_segment')

corr = 1 / np.mean(sps.hann(nperseg, sym=False) ** 2)

assert_allclose(np.sqrt(np.trapz(corr * p_xrft.values, p_xrft.freq_t.values)), A*np.sqrt(2)/2,
                rtol=1e-3)
```

2021-02-09 07:22 UTC, roxyboy commented
> My only concern with having "amplitude" in the name is that there is a _different_ correction that specifically corrects the amplitude of the spectrum (rather than its integral/energy). So I worry that `boost_amplitude` could be confusing for users.

I changed it to `boost_windowed_amplitude`.

2021-02-09 18:16 UTC, roxyboy commented
Ok, I've made all the changes suggested. I think this is ready to merge. @rabernat ??

2021-02-09 18:25 UTC, roxyboy commented
> And using `xrft`:
> 
> ```python
> x_da = xr.DataArray(x, coords=[tt], dims=['t']).chunk({'t': nperseg})
> 
> p_xrft = xrft.xrft.power_spectrum(x_da, 
>                                   dim=['t'],
>                                   window=True,
>                                   chunks_to_segments=True).mean('t_segment')
> 
> corr = 1 / np.mean(sps.hann(nperseg, sym=False) ** 2)
> 
> assert_allclose(np.sqrt(np.trapz(corr * p_xrft.values, p_xrft.freq_t.values)), A*np.sqrt(2)/2,
>                 rtol=1e-3)
> ```

Actually, this test is supposed to hold for `boost_windowed_amplitude = True`??

2021-02-09 20:31 UTC, dougiesquire commented
> > And using `xrft`:
> > 
> > ```python
> > x_da = xr.DataArray(x, coords=[tt], dims=['t']).chunk({'t': nperseg})
> > 
> > p_xrft = xrft.xrft.power_spectrum(x_da, 
> >                                   dim=['t'],
> >                                   window=True,
> >                                   chunks_to_segments=True).mean('t_segment')
> > 
> > corr = 1 / np.mean(sps.hann(nperseg, sym=False) ** 2)
> > 
> > assert_allclose(np.sqrt(np.trapz(corr * p_xrft.values, p_xrft.freq_t.values)), A*np.sqrt(2)/2,
> >                 rtol=1e-3)
> > ```
> 
> Actually, this test is supposed to hold for `boost_windowed_amplitude = True`?? As of now, it seems to be passing for `boost_windowed_amplitude = False`...

Do you mean in your implementation or in the above? In the above, I have applied the correction with the `corr` variable. Without this, the test does not pass.

2021-02-09 20:34 UTC, roxyboy commented
> Do you mean in your implementation or in the above? In the above, I have applied the correction with the `corr` variable. Without this, the test does not pass.

Makes sense. Now the test is passing with `boost_windowed_amplitude = True` without the `corr` factor :)

2021-02-10 02:55 UTC, dougiesquire reviewed
Thanks for doing this @roxyboy. I've made a few minor comments.

I still think that `boost_windowed_amplitude` could be a confusing name for reasons I've outlined above. But, if other folks are happy with this name then I am too :)

2021-02-10 02:55 UTC, dougiesquire commented on xrft/xrft.py
> +                cs = cs / (windows ** 2).mean()
As above

2021-02-10 05:23 UTC, dougiesquire commented on xrft/xrft.py
> +                ps = ps / (windows ** 2).mean()
UPDATE: I've made a little progress in my understanding here. I'll provide an update on the main thread and see what folks think for moving forward.

2021-02-10 05:30 UTC, rabernat commented
I appreciate everyone's hard work on this. Sorry I haven't had more time to engage. I will try to review within a few days.

2021-02-10 06:15 UTC, dougiesquire commented
I've done a little more investigation and this is where I'm at:

Applying a non-uniform windowing weighting to a signal reduces its energy. There are two very commonly applied corrections for this:
1. __Amplitude correction__ - this corrects the amplitude of peaks in the spectrum. It is typically applied to the power spectrum (ie not density) and is most useful in strongly periodic signals. It ensures, for example, that the peak in the power spectrum of a 10 Hz sine wave with RMS=1.0 has a magnitude of 1.0. In scipy, this correction is applied by default when `scaling='spectrum'` without any option to turn it off.
2. __Energy correction__ - this corrects for the energy (integral) of the spectrum. It is typically applied to the power spectral density (including cross power spectral density). It ensures that the integral of the spectral density (approximately) matches the square of the RMS of the signal. In scipy, this correction is applied by default when `scaling='density'` without any option to turn it off.

The energy correction is only exact when the signal being windowed is independent of the window. It gets more accurate as the width of the window gets large in comparison with any noticeable period in the signal (see discussion here: https://dsp.stackexchange.com/questions/47598/does-windowing-affect-parsevals-theorem). This is why we can't exactly satisfy Parseval's theorem with the energy correction.

Moving forward, I propose that we add an option (e.g. `window_correction`) that matches the behaviour of scipy. That is:
- With `window_correction = True` and `scaling='density'`, the energy correction is applied
- With `window_correction = True` and `scaling='spectrum'`, the amplitude correction is applied.

I'll write out below specifically how these are applied and how we can test their implementation.

What became very clear to me while trying to read about this is that there is a lot of confusion around these corrections and whether/how they're applied in a variety of software. So, whatever we decide to do, let's try and document it very clearly!

2021-02-10 17:29 UTC, roxyboy commented on xrft/xrft.py
> +                ps = ps / (windows ** 2).mean()
The correction applied in scipy is `.sum()` while I've currently implemented the correction as `.mean()`. We should apply the correction with `.sum()`...?

2021-02-11 05:48 UTC, dougiesquire commented on xrft/xrft.py
> +                ps = ps / (windows ** 2).mean()
`mean()` is correct with the current implementation.

This is because scaling by the sampling frequency (or it's square if `scaling='spectrum'`) is done as a separate step in xrft, whereas scipy does all the scaling in one hit with the `scale` variable (https://github.com/scipy/scipy/blob/master/scipy/signal/spectral.py#L1798). It's simple to show that by using the `mean()` instead of the `sum()` to compute our corrections, we end up with the same final scaling as scipy.

2021-02-11 07:23 UTC, dougiesquire commented
Sorry, it took me a while to get to this. I think @roxyboy has already added some of what I summarise below. But just documenting here for clarity.
 
With the scaling that is already applied to the spectrum within xrft, the correction factors are computed as follows:
 
__Energy correction__:
```python
correction = 1.0 / (window ** 2).mean()
```
__Amplitude correction__:
```python
correction = 1.0 / window.mean() ** 2
```
 
With these applied when `scaling='density'` and `'spectrum'`, respectively, xrft will give the same results as scipy.
 
We can test these by borrowing scipy's test function:
```python
A = 20
fs = 1e4
n_segments = int(fs // 10)
fsig = 300

tt = np.arange(fs) / fs
x = A * np.sin(2 * np.pi * fsig * tt)

for window_type in ["hann", "bartlett", "tukey", "flattop"]:
    # See https://github.com/scipy/scipy/blob/master/scipy/signal/tests/test_spectral.py#L485

    x_da = xr.DataArray(x, coords=[tt], dims=["t"]).chunk({"t": n_segments})
    
    p_dens = xrft.xrft.power_spectrum(
        x_da,
        dim=["t"],
        window=window_type,
        chunks_to_segments=True,
        scaling='density',
        window_correction=True,
    ).mean("t_segment")
    
    p_spec = xrft.xrft.power_spectrum(
        x_da,
        dim=["t"],
        window=window_type,
        chunks_to_segments=True,
        scaling='spectrum',
        window_correction=True,
    ).mean("t_segment")

    # Check the energy correction for p_dens
    npt.assert_allclose(
        np.sqrt(np.trapz(p_dens.values, p_dens.freq_t.values)),
        A * np.sqrt(2) / 2,
        rtol=1e-3)
    
    # Check the amplitude correction for p_spec
    # The factor of 0.5 is there because we're checking the two-sided spectrum
    npt.assert_allclose(
        p_spec.sel(freq_t=fsig),
        0.5 * A ** 2 / 2.0) 
```

2021-02-11 07:29 UTC, roxyboy commented
> Sorry, it took me a while to get to this. I think @roxyboy has already added some of what I summarise below. But just documenting here for clarity.
> 
> With the scaling that is already applied to the spectrum within xrft, the correction factors are computed as follows:
> 
> **Energy correction**:
> 
> ```python
> correction = 1.0 / (window ** 2).mean()
> ```
> 
> **Amplitude correction**:
> 
> ```python
> correction = 1.0 / window.mean() ** 2
> ```
> 
> With these applied when `scaling='density'` and `'spectrum'`, respectively, xrft will give the same results as scipy.
> 
> We can test these by borrowing scipy's test function:
> 
> ```python
> A = 20
> fs = 1e4
> n_segments = int(fs // 10)
> fsig = 300
> 
> tt = np.arange(fs) / fs
> x = A * np.sin(2 * np.pi * fsig * tt)
> 
> for window_type in ["hann", "bartlett", "tukey", "flattop"]:
>     # See https://github.com/scipy/scipy/blob/master/scipy/signal/tests/test_spectral.py#L485
> 
>     x_da = xr.DataArray(x, coords=[tt], dims=["t"]).chunk({"t": n_segments})
>     
>     p_dens = xrft.xrft.power_spectrum(
>         x_da,
>         dim=["t"],
>         window=window_type,
>         chunks_to_segments=True,
>         scaling='density',
>         window_correction=True,
>     ).mean("t_segment")
>     
>     p_spec = xrft.xrft.power_spectrum(
>         x_da,
>         dim=["t"],
>         window=window_type,
>         chunks_to_segments=True,
>         scaling='spectrum',
>         window_correction=True,
>     ).mean("t_segment")
> 
>     # Check the energy correction for p_dens
>     npt.assert_allclose(
>         np.sqrt(np.trapz(p_dens.values, p_dens.freq_t.values)),
>         A * np.sqrt(2) / 2,
>         rtol=1e-3)
>     
>     # Check the amplitude correction for p_spec
>     # The factor of 0.5 is there because we're checking the two-sided spectrum
>     npt.assert_allclose(
>         p_spec.sel(freq_t=fsig),
>         0.5 * A ** 2 / 2.0) 
> ```

All done :)

2021-02-11 08:08 UTC, dougiesquire reviewed
Crikey you're efficient @roxyboy. Making changes as I review!

All looks good to me I think. Thanks for persevering here. I think this is a useful addition and it's great to also now have the option to use all the scipy window functions.

2021-02-11 08:08 UTC, dougiesquire commented on xrft/xrft.py
> +                        raise ValueError("Windowing needs to be turned on.")
Maybe a little more verbose, e.g
"window_correction can only be applied when a non-uniform window is applied"
or, this could just silently do nothing?

2021-02-11 08:08 UTC, dougiesquire commented on xrft/xrft.py
> +                        warnings.warn(msg, Warning)
This could get quite annoying. Do we really need a warning every time the user chooses to use this parameter?

2021-02-11 08:08 UTC, dougiesquire commented on xrft/xrft.py
> +                    if kwargs[arg] is None:
Same comments as above

2021-02-11 08:08 UTC, dougiesquire commented on xrft/xrft.py
> +        If True, it will correct for the energy reduction resulting from applying a non-uniform window.
As above

2021-02-11 08:08 UTC, dougiesquire commented on xrft/xrft.py
> +                        msg = "Energy correction is applied where the integral of the spectral density (approximately) matches the square of the RMS of the input signal."
As above

2021-02-11 08:08 UTC, dougiesquire commented on xrft/xrft.py
> +                        msg = "Amplitude correction is applied which corrects the amplitude of peaks in the spectrum."
As above

2021-02-11 17:38 UTC, roxyboy commented on xrft/xrft.py
> +                        warnings.warn(msg, Warning)
I personally would... but that's only my opinion.

2021-02-11 17:38 UTC, roxyboy commented on xrft/xrft.py
> +                        warnings.warn(msg, Warning)
I personally would... but that's only my opinion. Perhaps others could chime in @navidcy, @rabernat, @lanougue

2021-02-11 17:39 UTC, roxyboy commented on xrft/xrft.py
> +                        raise ValueError("Windowing needs to be turned on.")
Silently doing nothing is definitely going to confuse users.

2021-02-11 17:46 UTC, roxyboy commented on xrft/xrft.py
> +                        warnings.warn(msg, Warning)
Users can suppress warnings when they use any package fwiw.

2021-02-11 18:04 UTC, lanougue commented
Sorry for not being of any help here. I am in the middle of a satellite cal/Val campaign. On a boat with stomach upside down....

2021-02-11 18:05 UTC, roxyboy commented
@lanougue Good luck on the cruise! Cal/Val for SWOT??

2021-02-12 08:24 UTC, lanougue commented
> @lanougue Good luck on the cruise! Cal/Val for SWOT??
Thanks @roxyboy,
One month cruise for CFOSAT this time... Maybe later for SWOT.

2021-02-15 14:34 UTC, rabernat commented
Is this ready for me to review now?

2021-02-15 14:35 UTC, roxyboy commented
> Is this ready for me to review now?

@rabernat I believe so. I don't intend to make further edits for this PR.

2021-02-15 16:21 UTC, rabernat requested changes
Thanks so much for everyone's work on this! Overall it seems great.

My main concern is that we are trying to use warnings where we should be using documentation. I don't think this PR is complete without __narrative documentation__ that fully explains all of the different choices for `window`, `scaling`, `wind_corrections`, `real` etc. These options are too complex to expect people will figure them out via a doc string.

Is it safe to assume that these examples will be part of #135? If so, then we can skip that here. But let's recognize that they are closely coupled.

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +        transform is taken. Please adhere to scipy.signal.windows for naming convention.
Is `window` allowed to be a string (e.g. `window="Hann"`)? If so, the docstring needs an update (change `bool`).

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +        transform is taken. Please adhere to scipy.signal.windows for naming convention.
Same.

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +                if arg == "window":
Why do we need to iterate through the args here?

Why not `window = kwargs.get("window", None)`?

That would let you reduce the level of nesting.

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +                        warnings.warn(msg, Warning)
I'm not sure I understand what to do with this warning. It seems like a simple description of what the option does. That belongs in the documentation. Why does that merit a warning? How should a user respond when they see it? What action do you hope to provoke from the user?

I suspect that the warning is here because some users may find this behavior unexpected. (But then why would they ask for window_correction=True?) Is there an alternative behavior they can turn on? How?

In summary, if we use a warning, let's try to have the warning suggest a concrete action the user can take to mitigate confusion or avoid incorrect / unwanted results. The warning should not appear every time a user uses a specific option, unless that option is deprecated.

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +                        msg = "Amplitude correction is applied which corrects the amplitude of peaks in the spectrum."
same comment about warnings.

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +            "Please adhere to scipy.signal.windows for naming convention."
```suggestion
            f"Window type {window_type} not supported. Please adhere to scipy.signal.windows for naming convention."
```

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +        ps = ps * xr.DataArray(f, dims=real_dim)
Are we sure this multiplication works if `ps` has coordinates?

2021-02-15 16:21 UTC, rabernat commented on xrft/xrft.py
> +    real : str, optional
```suggestion
    real_dim : str, optional
```

I think it would be easier to understand this argument if it were explicitly named `real_dim`.

2021-02-15 17:52 UTC, roxyboy commented
> My main concern is that we are trying to use warnings where we should be using documentation. I don't think this PR is complete without **narrative documentation** that fully explains all of the different choices for `window`, `scaling`, `wind_corrections`, `real` etc. These options are too complex to expect people will figure them out via a doc string.
> 
> Is it safe to assume that these examples will be part of #135? If so, then we can skip that here. But let's recognize that they are closely coupled.

I 100% agree with this and a better documentation is on my to-do list as part of PR #135 .

2021-02-15 18:41 UTC, roxyboy commented
Well, this is annoying... The tests are passing locally...

2021-02-15 18:57 UTC, roxyboy commented
@rabernat I implemented your changes :) Can we merge this?

2021-02-15 21:10 UTC, navidcy commented
I agree with @rabernat that serious update of docs is in order. But given that this will happen in a sister-PR soon then I'm also in favor of going forward with this.

(I'm happy to help with the docs-PR, but somebody needs to show me how to compile/view docs locally :))

2021-02-15 21:11 UTC, navidcy commented
Also note that there are breaking changes in this PR (e.g., `real`->`real_dim`) so a new minor release should follow (after doc-PR is settled).

2021-02-15 21:17 UTC, dougiesquire commented
> I agree with @rabernat that serious update of docs is in order. But given that this will happen in a sister-PR soon then I'm also in favor of going forward with this.
> 
> (I'm happy to help with the docs-PR, but somebody needs to show me how to compile/view docs locally :))

I'm in the same boat here - help to help with #135 if/where I can, but don't know how best to contribute to the notebook.

2021-02-17 08:35 UTC, roxyboy commented
Seems like everyone is happy with this PR so I'm gonna merge this so that we can start working on the documentation :)

2021-02-17 08:35 UTC, merged

2021-02-17 14:00 UTC, rabernat commented
> Also note that there are breaking changes in this PR (e.g., `real`->`real_dim`) so a new minor release should follow (after doc-PR is settled).

Have we actually done a release that includes the `real` option? If so, we should do a deprecation cycle for this.

2021-02-17 17:32 UTC, navidcy commented
> > Also note that there are breaking changes in this PR (e.g., `real`->`real_dim`) so a new minor release should follow (after doc-PR is settled).
> 
> Have we actually done a release that includes the `real` option? If so, we should do a deprecation cycle for this.

Agreed. I think several releases lately included the `real` option in `dft`.

2021-02-17 18:04 UTC, roxyboy commented
> > > Also note that there are breaking changes in this PR (e.g., `real`->`real_dim`) so a new minor release should follow (after doc-PR is settled).
> > 
> > 
> > Have we actually done a release that includes the `real` option? If so, we should do a deprecation cycle for this.
> 
> Agreed. I think several releases lately included the `real` option in `dft`.

I've started PR #139 to address this.