Dft reverse axis
xgcm/xrft pull request #149
Opened 2021-04-20 09:57 UTC by lanougue

Handle decreasing coordinates in dft with true_phase = True.
Add a test to check

2021-04-22 22:15 UTC, lanougue commented
@roxyboy, merge ?

2021-04-23 08:04 UTC, roxyboy commented
I'm personally ok to merge but I think we should wait for @rabernat 's approval as well. He should be back from vacation next week.
We should also probably update the docs page using realistic data from the xarray tutorial (e.g. #148 ).

2021-04-26 15:35 UTC, rabernat requested changes
Thanks so much for this PR @lanougue! I really appreciate your work.

I agree with @roxyboy that documentation of this behavior is needed in the public facing docstrings and / or narrative documentation.

2021-04-26 15:35 UTC, rabernat commented on xrft/xrft.py
> +    )  # taking care of reverse coordinate (CAUTION : []  diff None)
I don't understand this comment, specifically `(CAUTION : []  diff None)`.

2021-04-26 15:35 UTC, rabernat commented on xrft/xrft.py
> +    lag = np.flip(coord.data, axis=reverse_coord)[(len(coord.data)) // 2]
For the sake of the other devs, I would prefer to make this all a bit more explicit, i.e.
```python
if coord[-1] > coord[0]:
    coord_data = np.flip(coord.data, axis=-1)
else:
    coord_data = coord.data
lag = coord_data / (len(coord.data) // 2)
```

2021-04-26 17:06 UTC, lanougue commented on xrft/xrft.py
> +    )  # taking care of reverse coordinate (CAUTION : []  diff None)
Sorry for this not being explicit. This is to emphasize that:
np.flip(a, axis=None) has a different behaviour than np.flip(a, axis=[]).
If axis=None, all axis are flipped.
If axis=[], no axis are flipped
I though it deserved to me mentioned in a comment

2021-04-26 17:08 UTC, lanougue commented on xrft/xrft.py
> +    lag = np.flip(coord.data, axis=reverse_coord)[(len(coord.data)) // 2]
ok but the last line should then be:
`lag = coord_data[(len(coord.data)) // 2]`

2021-04-26 19:16 UTC, rabernat commented
Thanks! So is the plan to defer the documentation updates to a future PR? If so, I will merge.

2021-04-26 19:20 UTC, roxyboy commented
> Thanks! So is the plan to defer the documentation updates to a future PR? If so, I will merge.

I give a thumbs up to a separate PR for docs :)

2021-04-26 19:29 UTC, merged