Storing lag for round-tripping
xgcm/xrft pull request #157
Opened 2021-06-15 22:16 UTC by lanougue

In this PR, I store the lag of the transformed dimension as an attribute of the new coordinates (same as "spacing").
This seems logical (to me) and ensures that this attributes will not be accidentally erased when applying some transformation/operation (filtering most probably) on the transformed array.

2021-06-15 22:28 UTC, lanougue commented
@roxyboy, I am really not smart enough to understand these pre-commit fails...
Any suggestion ?

2021-06-15 22:29 UTC, roxyboy requested changes

2021-06-15 22:29 UTC, roxyboy commented on xrft/xrft.py
> +    if lag is None:
This is a great start. Thanks for the PR. I think we want to go one step further and now use this "direct_lag" object in xrft.idft to get out the original coordinates in `da`, i.e. da.coords = xrft.idft(xrft.dft(da)).coords.

2021-06-15 22:30 UTC, roxyboy commented
> @roxyboy, I am really not smart enough to understand these pre-commit fails...
> Any suggestion ?

Probably just has to do with black formatting. Running `black xrft.py` should fix it (assuming you have black installed).

2021-06-15 22:35 UTC, lanougue commented on xrft/xrft.py
> +    if lag is None:
Yes, this is exactly what this PR is doing.
Now DA =  xrft.idft(xrft.dft(da)) will have the same coordinates as da
(when using true_phase = true in both calls)

2021-06-15 22:41 UTC, lanougue commented
> > @roxyboy, I am really not smart enough to understand these pre-commit fails...
> > Any suggestion ?
> 
> Probably just has to do with black formatting. Running `black xrft.py` should fix it (assuming you have black installed).

When I commit, black says that it passes the test (when black test fails, black corrects the files and the test passes when doing a new commit). I thus do not understand why it fails on github ...

2021-06-16 07:15 UTC, roxyboy commented on xrft/xrft.py
> +    if lag is None:
Great! Can you add a test to check this??

2021-06-16 09:01 UTC, lanougue commented on xrft/xrft.py
> +    if lag is None:
Sure ! Done

2021-06-16 11:45 UTC, roxyboy commented on xrft/tests/test_xrft.py
>      xrt.assert_allclose(s, IFTs)
Sorry, this is an elementary question but does xarray.testing also check for the coordinates?

2021-06-16 12:34 UTC, lanougue commented on xrft/tests/test_xrft.py
>      xrt.assert_allclose(s, IFTs)
Yes, I verified manually.

However, with these changes default behaviour of idft has changed. By default (lag=None), output coordinates were centered. Now, the default is to use the direct_lag value. Maybe it deserves some warning

2021-06-16 13:03 UTC, roxyboy commented on xrft/tests/test_xrft.py
>      xrt.assert_allclose(s, IFTs)
Mmm, I feel like the `idft` functionality hasn't been around long enough to warrant a deprecation cycle so I think a warning would suffice. @rabernat Would you agree with this?

2021-07-01 18:57 UTC, roxyboy commented
@lanougue Is this ready to merge?

2021-07-02 10:26 UTC, lanougue commented
yes !

2021-07-02 10:28 UTC, merged