Explicit error when coordinates are not numercial
xgcm/xrft pull request #190
Opened 2023-01-17 17:45 UTC by lanougue

2023-01-18 16:41 UTC, lanougue commented
@roxyboy The checks do not seem to be processed. Any idea why ?

2023-01-18 18:26 UTC, roxyboy commented on xrft/xrft.py
> +    if not np.all([is_numeric_dtype(da.coords[d]) for d in dim]): # checking if coodinates are numerical
Thanks, I like this check :)

2023-01-18 18:28 UTC, roxyboy requested changes

2023-01-20 13:47 UTC, lanougue commented on xrft/xrft.py
> +    from pandas.api.types import is_numeric_dtype
Done

2023-01-23 17:36 UTC, lanougue commented
> > @roxyboy The checks do not seem to be processed. Any idea why ?
> 
> @jbusecke Any ideas on why the Pytests are halted..?

Hi @roxyboy ,
Maybe something linked to workflow or rule protection of branches. See link below
https://github.com/orgs/community/discussions/26698

2023-02-06 18:42 UTC, lanougue commented
@rabernat @roxyboy , hello guys, it would be nice to have this new xrft release ! Can you have a look on how to resolve this PR checks ? it could ease the final formatting of these modifications. Thanks !
Cheers

2023-02-06 21:22 UTC, roxyboy approved these changes
These edits look good, thanks :) Regarding the stalled tests, I did take a look at the [link](https://github.com/orgs/community/discussions/26698) but I couldn't seem to understand the fix... I've asked an expert so hopefully he'll reply soon.

2023-02-06 21:49 UTC, cisaacstern commented
Thanks for looping me in here @roxyboy! I've been digging around on SO and the best guess I have so far, based on [this post](https://stackoverflow.com/a/69169858), is that perhaps the fact that this PR's first commit was a `Verified` commit made via the GitHub web browser is somehow causing problems. One of the suggested solutions in that SO post is to close and then re-open the PR, so I will try that now.

2023-02-06 21:50 UTC, cisaacstern commented
🤔 Ok that did not seem to work...

2023-02-06 22:04 UTC, cisaacstern commented
@roxyboy and I are coordinating offline on this... he has just removed the requirement in the repo settings that status checks must pass before a PR is merged. From further reading on Stack Overflow it seems this requirement can sometimes interfere with CI running, as we are observing here. I will now close and re-open this PR to re-trigger CI.

2023-02-06 22:05 UTC, jbusecke commented
Ah ok, sorry then Ill close #193

2023-02-06 22:05 UTC, cisaacstern commented
Looks like that unblocked us! 🎉 

<img width="600" alt="Screen Shot 2023-02-06 at 2 05 04 PM" src="https://user-images.githubusercontent.com/62192187/217098154-108f2412-d079-4f64-874d-eac47e393da8.png">

2023-02-06 22:05 UTC, roxyboy commented
> Looks like that unblocked us! 🎉
> 
> <img alt="Screen Shot 2023-02-06 at 2 05 04 PM" width="600" src="https://user-images.githubusercontent.com/62192187/217098154-108f2412-d079-4f64-874d-eac47e393da8.png">

Yes, it's looking promising!

2023-02-06 22:06 UTC, roxyboy commented
For the future, should I just keep "Require status checks to pass" unchecked..?

2023-02-06 22:07 UTC, cisaacstern commented
> Ah ok, sorry then Ill close https://github.com/xgcm/xrft/pull/193

@jbusecke thanks! Takaya looped me in and I didn't realize that you'd opened that PR so just decided to "test in production" 😆 .

2023-02-06 22:07 UTC, cisaacstern commented
> For the future, should I just keep "Require status checks to pass" unchecked..?

@roxyboy I think this is the easiest path forward for now, yes.

2023-02-06 22:13 UTC, roxyboy commented
@lanougue It seems that the tests are failing from `xarray.ufunc` being deprecated..?

2023-02-07 12:55 UTC, lanougue commented
@roxyboy yes, this is why I opened PR #191. I will do both of these modifications in this PR in order to make the tests to pass.

2023-02-08 15:51 UTC, lanougue commented
@roxyboy I think this is it !

2023-02-08 15:55 UTC, roxyboy commented on xrft/xrft.py
> +                or bool(getattr(da.coords[d][0].item(), "calendar", False))
@lanougue Could you explain what this new condition is for...?

2023-02-08 16:10 UTC, lanougue commented on xrft/xrft.py
> +                or bool(getattr(da.coords[d][0].item(), "calendar", False))
xrft.fft can do Fourier Transforms on data with coordinates being of dtype "cftime" (some kind of temporal data with a defined calendar). In the test_xrft.py file, we have some checks with this kind of coordinates with  "julian", "365_day", "360_day" type of calendar.
When coordinates are of cftime type, the returned dtype is "object" which is not considered as "numerical" or "datetime" by pandas API. It is thus needed to have some special test to accept this kind of data if we want to pass the checks.

2023-02-08 16:12 UTC, roxyboy commented on xrft/xrft.py
> +                or bool(getattr(da.coords[d][0].item(), "calendar", False))
Ok, sounds good. I'll go ahead and merge this :)

2023-02-08 16:12 UTC, merged